channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=25.2
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==2.0.2
  - pandas==2.2.3
  - scikit-learn==1.5.2
  - scipy==1.16.2
name: mlflow-env